/**
 * Mock data for courses - will be replaced with API calls
 */

import {
  Category,
  Course,
  CourseDetail,
  CourseSearchResult,
  EnrolledCourse,
  Review,
  Section,
} from "@/types/course";

export const mockCategories: Category[] = [
  { id: "1", name: "Toán học", slug: "math", icon: "calculator" },
  { id: "2", name: "Khoa học", slug: "science", icon: "flask" },
  { id: "3", name: "Tiếng Anh", slug: "english", icon: "book" },
  { id: "4", name: "Công nghệ", slug: "technology", icon: "code" },
  { id: "5", name: "Lịch sử", slug: "history", icon: "scroll" },
  { id: "6", name: "Văn học", slug: "literature", icon: "pen" },
];

const createMockInstructor = (id: string, name: string) => ({
  id,
  name,
  avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=${name}`,
  title: "Giảng viên chính",
  bio: "Giảng viên với hơn 10 năm kinh nghiệm trong lĩnh vực giáo dục.",
  courseCount: Math.floor(Math.random() * 10) + 3,
  studentCount: Math.floor(Math.random() * 5000) + 1000,
  rating: 4.5 + Math.random() * 0.4,
});

export const mockCourses: Course[] = [
  {
    id: "1",
    title: "Toán học cơ bản cho học sinh THPT",
    slug: "toan-hoc-co-ban-thpt",
    description: "Khóa học toán học toàn diện dành cho học sinh trung học phổ thông.",
    thumbnail: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800",
    price: 0,
    rating: 4.8,
    reviewCount: 120,
    studentCount: 1234,
    instructor: createMockInstructor("i1", "Nguyễn Văn A"),
    category: mockCategories[0],
    level: "beginner",
    language: "Tiếng Việt",
    duration: 1200,
    lessonCount: 45,
    learningOutcomes: [
      "Nắm vững kiến thức toán học cơ bản",
      "Giải các bài toán phức tạp",
      "Chuẩn bị cho kỳ thi THPT Quốc gia",
    ],
    createdAt: "2024-01-15",
    updatedAt: "2024-03-01",
    isFeatured: true,
    isPublished: true,
  },
  {
    id: "2",
    title: "Lập trình Python từ cơ bản đến nâng cao",
    slug: "lap-trinh-python-co-ban-nang-cao",
    description: "Học Python từ số 0, bao gồm cả ứng dụng thực tế và dự án.",
    thumbnail: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800",
    price: 500000,
    originalPrice: 750000,
    rating: 4.9,
    reviewCount: 256,
    studentCount: 3421,
    instructor: createMockInstructor("i2", "Trần Thị B"),
    category: mockCategories[3],
    level: "beginner",
    language: "Tiếng Việt",
    duration: 2400,
    lessonCount: 80,
    learningOutcomes: [
      "Hiểu các khái niệm lập trình cơ bản",
      "Xây dựng ứng dụng Python thực tế",
      "Làm việc với dữ liệu và API",
    ],
    createdAt: "2024-02-01",
    updatedAt: "2024-03-10",
    isFeatured: true,
    isPublished: true,
  },
  {
    id: "3",
    title: "IELTS Writing Band 7.0+",
    slug: "ielts-writing-band-7",
    description: "Chiến lược và kỹ thuật viết IELTS để đạt band 7.0 trở lên.",
    thumbnail: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800",
    price: 800000,
    rating: 4.7,
    reviewCount: 89,
    studentCount: 892,
    instructor: createMockInstructor("i3", "Lê Văn C"),
    category: mockCategories[2],
    level: "intermediate",
    language: "Tiếng Việt",
    duration: 1800,
    lessonCount: 60,
    learningOutcomes: [
      "Viết Task 1 và Task 2 hiệu quả",
      "Mở rộng vốn từ vựng học thuật",
      "Tránh các lỗi phổ biến",
    ],
    createdAt: "2024-01-20",
    updatedAt: "2024-02-28",
    isPublished: true,
  },
  {
    id: "4",
    title: "Vật lý lượng tử cho người mới bắt đầu",
    slug: "vat-ly-luong-tu-nguoi-moi",
    description: "Khám phá thế giới vi mô và các nguyên lý vật lý lượng tử.",
    thumbnail: "https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?w=800",
    price: 350000,
    rating: 4.6,
    reviewCount: 45,
    studentCount: 456,
    instructor: createMockInstructor("i4", "Phạm Thị D"),
    category: mockCategories[1],
    level: "advanced",
    language: "Tiếng Việt",
    duration: 900,
    lessonCount: 30,
    learningOutcomes: [
      "Hiểu nguyên lý bất định Heisenberg",
      "Nắm vững phương trình Schrödinger",
      "Ứng dụng trong công nghệ hiện đại",
    ],
    createdAt: "2024-02-15",
    updatedAt: "2024-03-05",
    isPublished: true,
  },
  {
    id: "5",
    title: "Lịch sử Việt Nam thời kỳ phong kiến",
    slug: "lich-su-viet-nam-phong-kien",
    description: "Tìm hiểu về lịch sử hào hùng của dân tộc Việt Nam.",
    thumbnail: "https://images.unsplash.com/photo-1461360370896-922624d12a74?w=800",
    price: 0,
    rating: 4.5,
    reviewCount: 67,
    studentCount: 789,
    instructor: createMockInstructor("i5", "Hoàng Văn E"),
    category: mockCategories[4],
    level: "beginner",
    language: "Tiếng Việt",
    duration: 600,
    lessonCount: 20,
    learningOutcomes: [
      "Nắm vững các triều đại phong kiến",
      "Hiểu bối cảnh lịch sử",
      "Phân tích sự kiện lịch sử",
    ],
    createdAt: "2024-01-10",
    updatedAt: "2024-02-20",
    isPublished: true,
  },
  {
    id: "6",
    title: "React.js - Xây dựng ứng dụng web hiện đại",
    slug: "reactjs-xay-dung-ung-dung-web",
    description: "Học React.js từ cơ bản đến nâng cao, bao gồm hooks và state management.",
    thumbnail: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800",
    price: 650000,
    originalPrice: 900000,
    rating: 4.9,
    reviewCount: 312,
    studentCount: 4521,
    instructor: createMockInstructor("i6", "Nguyễn Thị F"),
    category: mockCategories[3],
    level: "intermediate",
    language: "Tiếng Việt",
    duration: 3000,
    lessonCount: 100,
    learningOutcomes: [
      "Xây dựng ứng dụng React hoàn chỉnh",
      "Quản lý state với Redux/Zustand",
      "Tích hợp API và xử lý dữ liệu",
    ],
    createdAt: "2024-02-10",
    updatedAt: "2024-03-12",
    isFeatured: true,
    isPublished: true,
  },
];

const mockSections: Section[] = [
  {
    id: "s1",
    title: "Giới thiệu khóa học",
    order: 1,
    duration: 45,
    completedLessons: 3,
    lessons: [
      { id: "l1", title: "Chào mừng đến với khóa học", duration: 10, type: "video", isFreePreview: true, completed: true, order: 1 },
      { id: "l2", title: "Cài đặt môi trường", duration: 20, type: "video", completed: true, order: 2 },
      { id: "l3", title: "Kiểm tra kiến thức ban đầu", duration: 15, type: "quiz", completed: true, order: 3 },
    ],
  },
  {
    id: "s2",
    title: "Kiến thức nền tảng",
    order: 2,
    duration: 90,
    completedLessons: 1,
    lessons: [
      { id: "l4", title: "Khái niệm cơ bản", duration: 25, type: "video", completed: true, order: 1 },
      { id: "l5", title: "Bài tập thực hành 1", duration: 30, type: "exercise", order: 2 },
      { id: "l6", title: "Tài liệu tham khảo", duration: 15, type: "reading", order: 3 },
      { id: "l7", title: "Kiểm tra chương 1", duration: 20, type: "quiz", order: 4 },
    ],
  },
  {
    id: "s3",
    title: "Nội dung nâng cao",
    order: 3,
    duration: 120,
    completedLessons: 0,
    lessons: [
      { id: "l8", title: "Chủ đề nâng cao 1", duration: 30, type: "video", order: 1 },
      { id: "l9", title: "Chủ đề nâng cao 2", duration: 30, type: "video", order: 2 },
      { id: "l10", title: "Dự án thực tế", duration: 45, type: "exercise", order: 3 },
      { id: "l11", title: "Kiểm tra cuối khóa", duration: 15, type: "quiz", order: 4 },
    ],
  },
];

const mockReviews: Review[] = [
  {
    id: "r1",
    user: { id: "u1", name: "Minh Tuấn", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=MinhTuan" },
    rating: 5,
    content: "Khóa học rất hay và chi tiết. Giảng viên giảng dễ hiểu, phù hợp cho người mới bắt đầu.",
    createdAt: "2024-03-01",
    helpful: 24,
  },
  {
    id: "r2",
    user: { id: "u2", name: "Thu Hà", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ThuHa" },
    rating: 4,
    content: "Nội dung tốt nhưng một số bài hơi dài. Nhìn chung vẫn rất đáng học.",
    createdAt: "2024-02-28",
    helpful: 15,
  },
  {
    id: "r3",
    user: { id: "u3", name: "Văn Đức", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=VanDuc" },
    rating: 5,
    content: "Xuất sắc! Đã hoàn thành khóa học và áp dụng được ngay vào công việc.",
    createdAt: "2024-02-25",
    helpful: 32,
  },
];

export const getMockCourseDetail = (slug: string): CourseDetail | null => {
  const course = mockCourses.find((c) => c.slug === slug);
  if (!course) return null;

  return {
    ...course,
    sections: mockSections,
    reviews: mockReviews,
    ratingDistribution: { 5: 60, 4: 25, 3: 10, 2: 3, 1: 2 },
    previewVideoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  };
};

export const mockEnrolledCourses: EnrolledCourse[] = [
  {
    ...mockCourses[0],
    progress: 60,
    completedLessons: 27,
    totalLessons: 45,
    lastAccessedAt: "2024-03-10T10:30:00Z",
    enrolledAt: "2024-02-01T08:00:00Z",
  },
  {
    ...mockCourses[1],
    progress: 25,
    completedLessons: 20,
    totalLessons: 80,
    lastAccessedAt: "2024-03-09T14:20:00Z",
    enrolledAt: "2024-02-15T09:00:00Z",
  },
];

export const mockSearchResults: CourseSearchResult[] = mockCourses.map((c) => ({
  id: c.id,
  title: c.title,
  thumbnail: c.thumbnail,
  instructor: c.instructor.name,
  slug: c.slug,
}));
