/**
 * Mock data for courses - will be replaced with API calls
 */

import {
  Category,
  Course,
  CourseDetail,
  CourseSearchResult,
  EnrolledCourse,
  Review,
  Section,
} from "@/types/course";

export const mockCategories: Category[] = [
  { id: "1", name: "Lập trình Web", slug: "web", icon: "code" },
  { id: "2", name: "Lập trình Mobile", slug: "mobile", icon: "smartphone" },
  { id: "3", name: "Backend & API", slug: "backend", icon: "server" },
  { id: "4", name: "DevOps & Cloud", slug: "devops", icon: "cloud" },
  { id: "5", name: "AI & Machine Learning", slug: "ai-ml", icon: "cpu" },
  { id: "6", name: "Cơ sở dữ liệu", slug: "database", icon: "database" },
];

const createMockInstructor = (id: string, name: string) => ({
  id,
  name,
  avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=${name}`,
  title: "Giảng viên chính",
  bio: "Giảng viên với hơn 10 năm kinh nghiệm trong lĩnh vực giáo dục.",
  courseCount: Math.floor(Math.random() * 10) + 3,
  studentCount: Math.floor(Math.random() * 5000) + 1000,
  rating: 4.5 + Math.random() * 0.4,
});

export const mockCourses: Course[] = [
  {
    id: "1",
    title: "React.js & Next.js - Xây dựng ứng dụng web hiện đại",
    slug: "reactjs-nextjs-web-hien-dai",
    description: "Học React.js và Next.js từ cơ bản đến nâng cao, bao gồm Server Components và App Router.",
    thumbnail: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800",
    price: 0,
    rating: 4.9,
    reviewCount: 456,
    studentCount: 5231,
    instructor: createMockInstructor("i1", "Nguyễn Văn A"),
    category: mockCategories[0],
    level: "beginner",
    language: "Tiếng Việt",
    duration: 3000,
    lessonCount: 100,
    learningOutcomes: [
      "Xây dựng ứng dụng React hoàn chỉnh",
      "Làm chủ Next.js App Router",
      "Triển khai ứng dụng lên Vercel",
    ],
    createdAt: "2024-01-15",
    updatedAt: "2024-03-01",
    isFeatured: true,
    isPublished: true,
  },
  {
    id: "2",
    title: "HTML CSS từ Zero đến Hero",
    slug: "html-css-zero-to-hero",
    description: "Lộ trình thực chiến HTML/CSS từ nền tảng đến xây dựng landing page và dashboard responsive.",
    thumbnail: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800",
    price: 0,
    rating: 4.8,
    reviewCount: 389,
    studentCount: 4872,
    instructor: createMockInstructor("i2", "Trần Thị B"),
    category: mockCategories[0],
    level: "beginner",
    language: "Tiếng Việt",
    duration: 2100,
    lessonCount: 72,
    learningOutcomes: [
      "Nắm vững semantic HTML và cấu trúc trang",
      "Làm chủ Flexbox, Grid và responsive layout",
      "Xây dựng UI hiện đại theo design system",
    ],
    createdAt: "2024-02-01",
    updatedAt: "2024-03-10",
    isFeatured: true,
    isPublished: true,
  },
  {
    id: "3",
    title: "Node.js & Express - Xây dựng REST API chuyên nghiệp",
    slug: "nodejs-express-rest-api",
    description: "Học Node.js và Express để xây dựng REST API, xử lý authentication và database.",
    thumbnail: "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=800",
    price: 500000,
    originalPrice: 750000,
    rating: 4.8,
    reviewCount: 312,
    studentCount: 3421,
    instructor: createMockInstructor("i3", "Lê Văn C"),
    category: mockCategories[2],
    level: "intermediate",
    language: "Tiếng Việt",
    duration: 2400,
    lessonCount: 80,
    learningOutcomes: [
      "Xây dựng REST API với Express",
      "Xác thực với JWT và OAuth",
      "Kết nối MongoDB và PostgreSQL",
    ],
    createdAt: "2024-02-01",
    updatedAt: "2024-03-10",
    isFeatured: true,
    isPublished: true,
  },
  {
    id: "3",
    title: "React Native - Lập trình ứng dụng di động đa nền tảng",
    slug: "react-native-mobile-app",
    description: "Học React Native để xây dựng ứng dụng iOS và Android từ một codebase duy nhất.",
    thumbnail: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800",
    price: 650000,
    originalPrice: 900000,
    rating: 4.7,
    reviewCount: 234,
    studentCount: 2890,
    instructor: createMockInstructor("i3", "Lê Văn C"),
    category: mockCategories[1],
    level: "intermediate",
    language: "Tiếng Việt",
    duration: 2800,
    lessonCount: 90,
    learningOutcomes: [
      "Xây dựng ứng dụng iOS và Android",
      "Sử dụng Redux và AsyncStorage",
      "Triển khai lên App Store và Google Play",
    ],
    createdAt: "2024-01-20",
    updatedAt: "2024-02-28",
    isPublished: true,
  },
  {
    id: "4",
    title: "Docker & Kubernetes - DevOps từ cơ bản đến nâng cao",
    slug: "docker-kubernetes-devops",
    description: "Học containerization và orchestration để deploy ứng dụng scale lớn.",
    thumbnail: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=800",
    price: 800000,
    rating: 4.8,
    reviewCount: 178,
    studentCount: 1567,
    instructor: createMockInstructor("i4", "Phạm Thị D"),
    category: mockCategories[3],
    level: "advanced",
    language: "Tiếng Việt",
    duration: 2200,
    lessonCount: 70,
    learningOutcomes: [
      "Containerize ứng dụng với Docker",
      "Orchestrate với Kubernetes",
      "CI/CD với GitHub Actions",
    ],
    createdAt: "2024-02-15",
    updatedAt: "2024-03-05",
    isPublished: true,
  },
  {
    id: "5",
    title: "Python cho AI & Machine Learning",
    slug: "python-ai-machine-learning",
    description: "Học Python, TensorFlow và PyTorch để xây dựng mô hình AI và ML thực tế.",
    thumbnail: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800",
    price: 0,
    rating: 4.9,
    reviewCount: 567,
    studentCount: 6789,
    instructor: createMockInstructor("i5", "Hoàng Văn E"),
    category: mockCategories[4],
    level: "beginner",
    language: "Tiếng Việt",
    duration: 3600,
    lessonCount: 120,
    learningOutcomes: [
      "Lập trình Python chuyên sâu",
      "Xây dựng mô hình ML với scikit-learn",
      "Deep Learning với TensorFlow và PyTorch",
    ],
    createdAt: "2024-01-10",
    updatedAt: "2024-02-20",
    isFeatured: true,
    isPublished: true,
  },
  {
    id: "6",
    title: "PostgreSQL & MongoDB - Quản lý cơ sở dữ liệu",
    slug: "postgresql-mongodb-database",
    description: "Học thiết kế và quản lý database với PostgreSQL (SQL) và MongoDB (NoSQL).",
    thumbnail: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800",
    price: 450000,
    originalPrice: 700000,
    rating: 4.6,
    reviewCount: 145,
    studentCount: 2134,
    instructor: createMockInstructor("i6", "Nguyễn Thị F"),
    category: mockCategories[5],
    level: "intermediate",
    language: "Tiếng Việt",
    duration: 1800,
    lessonCount: 60,
    learningOutcomes: [
      "Thiết kế schema quan hệ với PostgreSQL",
      "NoSQL với MongoDB",
      "Tối ưu hóa truy vấn và indexing",
    ],
    createdAt: "2024-02-10",
    updatedAt: "2024-03-12",
    isPublished: true,
  },
];

const mockSections: Section[] = [
  {
    id: "s1",
    title: "Giới thiệu khóa học",
    order: 1,
    duration: 45,
    completedLessons: 3,
    lessons: [
      { id: "l1", title: "Chào mừng đến với khóa học", duration: 10, type: "video", isFreePreview: true, completed: true, order: 1 },
      { id: "l2", title: "Cài đặt môi trường", duration: 20, type: "video", completed: true, order: 2 },
      { id: "l3", title: "Kiểm tra kiến thức ban đầu", duration: 15, type: "quiz", completed: true, order: 3 },
    ],
  },
  {
    id: "s2",
    title: "Kiến thức nền tảng",
    order: 2,
    duration: 90,
    completedLessons: 1,
    lessons: [
      { id: "l4", title: "Khái niệm cơ bản", duration: 25, type: "video", completed: true, order: 1 },
      { id: "l5", title: "Bài tập thực hành 1", duration: 30, type: "exercise", order: 2 },
      { id: "l6", title: "Tài liệu tham khảo", duration: 15, type: "reading", order: 3 },
      { id: "l7", title: "Kiểm tra chương 1", duration: 20, type: "quiz", order: 4 },
    ],
  },
  {
    id: "s3",
    title: "Nội dung nâng cao",
    order: 3,
    duration: 120,
    completedLessons: 0,
    lessons: [
      { id: "l8", title: "Chủ đề nâng cao 1", duration: 30, type: "video", order: 1 },
      { id: "l9", title: "Chủ đề nâng cao 2", duration: 30, type: "video", order: 2 },
      { id: "l10", title: "Dự án thực tế", duration: 45, type: "exercise", order: 3 },
      { id: "l11", title: "Kiểm tra cuối khóa", duration: 15, type: "quiz", order: 4 },
    ],
  },
];

const mockReviews: Review[] = [
  {
    id: "r1",
    user: { id: "u1", name: "Minh Tuấn", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=MinhTuan" },
    rating: 5,
    content: "Khóa học rất hay và chi tiết. Giảng viên giảng dễ hiểu, phù hợp cho người mới bắt đầu.",
    createdAt: "2024-03-01",
    helpful: 24,
  },
  {
    id: "r2",
    user: { id: "u2", name: "Thu Hà", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ThuHa" },
    rating: 4,
    content: "Nội dung tốt nhưng một số bài hơi dài. Nhìn chung vẫn rất đáng học.",
    createdAt: "2024-02-28",
    helpful: 15,
  },
  {
    id: "r3",
    user: { id: "u3", name: "Văn Đức", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=VanDuc" },
    rating: 5,
    content: "Xuất sắc! Đã hoàn thành khóa học và áp dụng được ngay vào công việc.",
    createdAt: "2024-02-25",
    helpful: 32,
  },
];

export const getMockCourseDetail = (slug: string): CourseDetail | null => {
  const course = mockCourses.find((c) => c.slug === slug);
  if (!course) return null;

  return {
    ...course,
    sections: mockSections,
    reviews: mockReviews,
    ratingDistribution: { 5: 60, 4: 25, 3: 10, 2: 3, 1: 2 },
    previewVideoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  };
};

export const mockEnrolledCourses: EnrolledCourse[] = [
  {
    ...mockCourses[0],
    progress: 60,
    completedLessons: 27,
    totalLessons: 45,
    lastAccessedAt: "2024-03-10T10:30:00Z",
    enrolledAt: "2024-02-01T08:00:00Z",
  },
  {
    ...mockCourses[1],
    progress: 25,
    completedLessons: 20,
    totalLessons: 80,
    lastAccessedAt: "2024-03-09T14:20:00Z",
    enrolledAt: "2024-02-15T09:00:00Z",
  },
];

export const mockSearchResults: CourseSearchResult[] = mockCourses.map((c) => ({
  id: c.id,
  title: c.title,
  thumbnail: c.thumbnail,
  instructor: c.instructor.name,
  slug: c.slug,
}));
