export interface Language {
  id: number;
  name: string;
  monaco: string;
  defaultCode: string;
}

export const LANGUAGES: Language[] = [
  { id: 43,  name: "Plain Text",                    monaco: "plaintext",   defaultCode: "Hello, World!" },
  { id: 45,  name: "Assembly (NASM 2.14.02)",       monaco: "plaintext",   defaultCode: 'section .data\n    msg db "Hello, World!", 10\n    len equ $ - msg\nsection .text\n    global _start\n_start:\n    mov eax, 4\n    mov ebx, 1\n    mov ecx, msg\n    mov edx, len\n    int 0x80\n    mov eax, 1\n    xor ebx, ebx\n    int 0x80' },
  { id: 46,  name: "Bash (5.0.0)",                  monaco: "shell",       defaultCode: '#!/bin/bash\necho "Hello, World!"' },
  { id: 47,  name: "Basic (FBC 1.07.1)",            monaco: "vb",          defaultCode: 'Print "Hello, World!"' },
  { id: 48,  name: "C (GCC 7.4.0)",                 monaco: "c",           defaultCode: '#include <stdio.h>\nint main() {\n    printf("Hello, World!\\n");\n    return 0;\n}' },
  { id: 49,  name: "C (GCC 8.3.0)",                 monaco: "c",           defaultCode: '#include <stdio.h>\nint main() {\n    printf("Hello, World!\\n");\n    return 0;\n}' },
  { id: 50,  name: "C (GCC 9.2.0)",                 monaco: "c",           defaultCode: '#include <stdio.h>\nint main() {\n    printf("Hello, World!\\n");\n    return 0;\n}' },
  { id: 75,  name: "C (Clang 7.0.1)",               monaco: "c",           defaultCode: '#include <stdio.h>\nint main() {\n    printf("Hello, World!\\n");\n    return 0;\n}' },
  { id: 51,  name: "C# (Mono 6.6.0.161)",           monaco: "csharp",      defaultCode: 'using System;\nclass Program {\n    static void Main() {\n        Console.WriteLine("Hello, World!");\n    }\n}' },
  { id: 52,  name: "C++ (GCC 7.4.0)",               monaco: "cpp",         defaultCode: '#include <iostream>\nusing namespace std;\nint main() {\n    cout << "Hello, World!" << endl;\n    return 0;\n}' },
  { id: 53,  name: "C++ (GCC 8.3.0)",               monaco: "cpp",         defaultCode: '#include <iostream>\nusing namespace std;\nint main() {\n    cout << "Hello, World!" << endl;\n    return 0;\n}' },
  { id: 54,  name: "C++ (GCC 9.2.0)",               monaco: "cpp",         defaultCode: '#include <iostream>\nusing namespace std;\nint main() {\n    cout << "Hello, World!" << endl;\n    return 0;\n}' },
  { id: 76,  name: "C++ (Clang 7.0.1)",             monaco: "cpp",         defaultCode: '#include <iostream>\nusing namespace std;\nint main() {\n    cout << "Hello, World!" << endl;\n    return 0;\n}' },
  { id: 77,  name: "COBOL (GnuCOBOL 2.2)",          monaco: "plaintext",   defaultCode: 'IDENTIFICATION DIVISION.\nPROGRAM-ID. HELLO.\nPROCEDURE DIVISION.\n    DISPLAY "Hello, World!".\n    STOP RUN.' },
  { id: 55,  name: "Common Lisp (SBCL 2.0.0)",      monaco: "plaintext",   defaultCode: '(format t "Hello, World!~%")' },
  { id: 86,  name: "Clojure (1.10.1)",              monaco: "clojure",     defaultCode: '(println "Hello, World!")' },
  { id: 56,  name: "D (DMD 2.089.1)",               monaco: "plaintext",   defaultCode: 'import std.stdio;\nvoid main() {\n    writeln("Hello, World!");\n}' },
  { id: 57,  name: "Elixir (1.9.4)",                monaco: "elixir",      defaultCode: 'IO.puts "Hello, World!"' },
  { id: 58,  name: "Erlang (OTP 22.2)",             monaco: "plaintext",   defaultCode: '-module(main).\n-export([start/0]).\nstart() ->\n    io:fwrite("Hello, World!~n").' },
  { id: 87,  name: "F# (.NET Core SDK 3.1.202)",    monaco: "fsharp",      defaultCode: 'printfn "Hello, World!"' },
  { id: 59,  name: "Fortran (GFortran 9.2.0)",      monaco: "plaintext",   defaultCode: "program hello\n    print *, 'Hello, World!'\nend program hello" },
  { id: 60,  name: "Go (1.13.5)",                   monaco: "go",          defaultCode: 'package main\nimport "fmt"\nfunc main() {\n    fmt.Println("Hello, World!")\n}' },
  { id: 88,  name: "Groovy (3.0.3)",                monaco: "plaintext",   defaultCode: 'println "Hello, World!"' },
  { id: 61,  name: "Haskell (GHC 8.8.1)",           monaco: "plaintext",   defaultCode: 'main :: IO ()\nmain = putStrLn "Hello, World!"' },
  { id: 62,  name: "Java (OpenJDK 13.0.1)",         monaco: "java",        defaultCode: 'public class Main {\n    public static void main(String[] args) {\n        System.out.println("Hello, World!");\n    }\n}' },
  { id: 63,  name: "JavaScript (Node.js 12.14.0)",  monaco: "javascript",  defaultCode: 'console.log("Hello, World!");' },
  { id: 78,  name: "Kotlin (1.3.70)",               monaco: "kotlin",      defaultCode: 'fun main() {\n    println("Hello, World!")\n}' },
  { id: 64,  name: "Lua (5.3.5)",                   monaco: "lua",         defaultCode: 'print("Hello, World!")' },
  { id: 65,  name: "OCaml (4.09.0)",                monaco: "plaintext",   defaultCode: 'let () = print_endline "Hello, World!"' },
  { id: 79,  name: "Objective-C (Clang 7.0.1)",     monaco: "objective-c", defaultCode: '#import <stdio.h>\nint main() {\n    printf("Hello, World!\\n");\n    return 0;\n}' },
  { id: 66,  name: "Octave (5.1.0)",                monaco: "plaintext",   defaultCode: "disp('Hello, World!')" },
  { id: 67,  name: "Pascal (FPC 3.0.4)",            monaco: "pascal",      defaultCode: "program Hello;\nbegin\n    WriteLn('Hello, World!');\nend." },
  { id: 85,  name: "Perl (5.28.1)",                 monaco: "perl",        defaultCode: 'print "Hello, World!\\n";' },
  { id: 68,  name: "PHP (7.4.1)",                   monaco: "php",         defaultCode: '<?php\necho "Hello, World!\\n";' },
  { id: 69,  name: "Prolog (GNU Prolog 1.4.5)",     monaco: "plaintext",   defaultCode: ":- initialization(main).\nmain :- write('Hello, World!'), nl." },
  { id: 70,  name: "Python (2.7.17)",               monaco: "python",      defaultCode: 'print "Hello, World!"' },
  { id: 71,  name: "Python (3.8.1)",                monaco: "python",      defaultCode: 'print("Hello, World!")' },
  { id: 80,  name: "R (4.0.0)",                     monaco: "r",           defaultCode: 'cat("Hello, World!\\n")' },
  { id: 72,  name: "Ruby (2.7.0)",                  monaco: "ruby",        defaultCode: 'puts "Hello, World!"' },
  { id: 73,  name: "Rust (1.40.0)",                 monaco: "rust",        defaultCode: 'fn main() {\n    println!("Hello, World!");\n}' },
  { id: 81,  name: "Scala (2.13.2)",                monaco: "scala",       defaultCode: 'object Main extends App {\n    println("Hello, World!")\n}' },
  { id: 82,  name: "SQL (SQLite 3.27.2)",           monaco: "sql",         defaultCode: "SELECT 'Hello, World!';" },
  { id: 83,  name: "Swift (5.2.3)",                 monaco: "swift",       defaultCode: 'print("Hello, World!")' },
  { id: 74,  name: "TypeScript (3.7.4)",            monaco: "typescript",  defaultCode: 'const msg: string = "Hello, World!";\nconsole.log(msg);' },
  { id: 84,  name: "Visual Basic.Net (vbnc 0.0.0.5943)", monaco: "vb",    defaultCode: 'Module Module1\n    Sub Main()\n        Console.WriteLine("Hello, World!")\n    End Sub\nEnd Module' },
];
